model_configs:
  protein_model_name_or_path: facebook/esm2_t30_150M_UR50D
  drug_model_name_or_path: "DeepChem/ChemBERTa-77M-MTR"
  model_hyperparameters:
    learning_rate: 0.001
    warmup_steps_ratio: 0.06
    protein_max_seq_len: 1024
    drug_max_seq_len: 512
    gradient_accumulation_steps: 32
    projected_size: 256
    projected_dropout: 0.3
  protein_fine_tuning_type: projection
  protein_peft_hyperparameters: null
  drug_fine_tuning_type: projection
  drug_peft_hyperparameters: null
  loss_function: cosine_mse
dataset_configs:
  dataset_name: BindingDB_random_drug
  split_method: random
training_configs:
  random_seed: 123
  device: 0
  patience: 75
  epochs: 150
  batch_size: 4
  outputs_dir: "outputs"
